blog/routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('post/{slug}', 'HomeController@showPage');
Route::get('category/{category}', 'HomeController@showCategory');
Route::get('search', 'HomeController@search');

Route::group(['prefix' => 'admin'], function(){
	Route::get('login', 'AuthAdminController@loginShowForm');
	Route::post('login', 'AuthAdminController@login')->name('login');
	Route::get('dashboard', 'AdminController@dashboard');
	Route::post('logout', 'AdminController@logout')->name('admin.logout');
	Route::resource('post','AdminPostController');
	Route::resource('category','AdminCategoryController');
	Route::resource('tag','AdminTagController');
	Route::post('search', 'AdminController@search');
});
	

blog/app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
}

blog/resources/views/admin/tags/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="box-body">
        <h4>Create Tags</h4>
        {{ Form::open(['url' => 'admin/tag', 'method' => 'post'])}}
            <div class="form-group" {{$errors->has('name') ? 'is-valid' : ''}}>
                <label for="name">Name</label>
                {{ Form::text('name', '', ['placeholder' => 'Name', 'class' => 'form-control']) }}
                {!! $errors->first('name','<small style="color:red;">:message</small>') !!}
            </div>
            <div class="form-group">
                {{ Form::submit('submit', ['class' => 'btn btn-success mr-2']) }}
            </div>  
        {{ form::close()}}
    </div>                               
@endsection

blog/resources/views/admin/tags/edit.blade.php
  @extends('layouts.admin')

  @section('content')
        {{ Form::open(['route' => ['tag.update', $tag->id], 'method' => 'post'])}}
        {{ method_field('PATCH') }}
        <div class="box-body">
            <h4>Edit Tags</h4>
            <div class="form-group" {{ $errors->has('name') ? 'is-invalid' : ''}}>
              <label for="title">name</label>
              {{ Form::text('name', $tag->name, ['placeholder' => 'Title', 'class' => 'form-control']) }}
              {!! $errors->first('name','<small style="color:red;">:message</small>') !!}
            </div>
            <div class="form-group">
              {{ Form::submit('submit', ['class' => 'btn btn-primary']) }}
            </div>  
        {{ form::close()}}           
    </div>      
@endsection

blog/resources/views/admin/tags/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h1>Tags</h1>
                    <a role="button" class="btn btn-success" href="tag/create">Create Tags</a>
                    <div style="float: right;">
                        {!! Form::open(['url' => 'admin/search', 'method' => 'post', 'class'=>'form navbar-form navbar-right searchform']) !!}
                            {!! Form::text('search', null,['class'=>'form-control','placeholder'=>'Search for a Post...']) !!}
                            {!! Form::submit('Search',['class'=>'btn btn-default']) !!}
                        {!! Form::close() !!}
                    </div>
                    <div class="table-responsive">
                        <table id="example2" class="table">
                            <thead>
                                <tr>
                                    <th><h4>Id</h4></th>
                                    <th><h4>Name</h4></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($tag as $row)
                                    <tr>
                                        <td>{{$row->id }}</td>
                                        <td>{{$row->name }}</td>
                                        <td>
                                            <a role="button" class="btn btn-primary" href="{{ URL::route('tag.edit', $row->id) }}">Edit</a>

                                                <form id="delete-form-{{ $row->id }}" method="post" action="{{ route('tag.destroy', $row->id) }}" style="display: none;">
                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}
                                                </form>
                                            <a class="btn btn-danger" href="{{ URL::route('tag.destroy', $row->id) }}" onclick="
                                                if (confirm('Are you really want to Delete This Post?')) {
                                                    event.preventDefault();
                                                    document.getElementById('delete-form-{{ $row->id }}').submit();
                                                } else {
                                                    event.preventDefault();
                                                }">Delete
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>    
                </div>
            </div>
        </div>
    </div>    
@endsection