blog/routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('post/{slug}', 'HomeController@showPage');
Route::get('category/{category}', 'HomeController@showCategory');
Route::get('search', 'HomeController@search');

Route::group(['prefix' => 'admin'], function(){
	Route::get('login', 'AuthAdminController@loginShowForm');
	Route::post('login', 'AuthAdminController@login')->name('login');
	Route::get('dashboard', 'AdminController@dashboard');
	Route::post('logout', 'AdminController@logout')->name('admin.logout');
	Route::resource('post','AdminPostController');
	Route::resource('category','AdminCategoryController');
	Route::resource('tag','AdminTagController');
	Route::post('search', 'AdminController@search');
});
	

blog/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    
}

blog/resources/views/admin/post/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="box-body">
        <h4>Create Post</h4>
        {{ Form::open(['url' => 'admin/post', 'method' => 'post', 'files' => true])}}
            {{-- <div class="form-group" {{$errors->has('user_id') ? 'is-valid' : ''}}>
                <label for="name">User Id</label>
                {{ Form::text('user_id', '', ['placeholder' => 'User Id','class' => 'form-control']) }}
                {!! $errors->first('user_id','<small style="color:red;">:message</small>') !!}
            </div> --}}
            <div class="form-group" {{$errors->has('title') ? 'is-valid' : ''}}>
                <label for="name">Title</label>
                {{ Form::text('title', '', ['placeholder' => 'Title', 'class' => 'form-control']) }}
                {!! $errors->first('title','<small style="color:red;">:message</small>') !!}
            </div>
             <div class="form-group" {{$errors->has('content') ? 'is-valid' : ''}}>
                <label for="name">Content</label>
                {{ Form::textarea('content', '', ['class' => 'form-control','id' => 'editor1'])}}
                {!! $errors->first('content','<small style="color:red;">:message</small>') !!}
            </div>
            <div class="form-group" {{$errors->has('file') ? 'is-valid' : ''}}>
                <label for="file">File Input</label>
                {{ Form::file('file', ['class' => 'form-control']) }}
                {!! $errors->first('file','<small style="color:red;">:message</small>') !!}
            </div> 
            <div class="form-group">
                <label for="category">Category</label>
                {{ Form::select('category_id', $data, '',['class' => 'form-control'] ) }}
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                {{ Form::select('tags[]', $tag,'', ['multiple' => 'multiple','class' => 'form-control tag']) }}
            </div>
            {{-- <div class="form-group" {{$errors->has('view_id') ? 'is-valid' : ''}}>
                <label for="name">View Id</label>
                {{ Form::text('view_id', '', ['placeholder' => 'view Id', 'class' => 'form-control']) }}
                {!! $errors->first('view_id','<small style="color:red;">:message</small>') !!}
            </div> --}}
            <div class="form-group">
                {{ Form::submit('submit', ['class' => 'btn btn-success mr-2']) }}
            </div>  
        {{ form::close()}}
    </div>                               
@endsection

blog/resources/views/admin/post/edit.blade.php
  @extends('layouts.admin')

  @section('content')
        {{ Form::open(['route' => ['post.update', $post->id], 'method' => 'post', 'files' => true])}}
        {{ method_field('PATCH') }}
        <div class="box-body">
            <h4>Edit Post</h4>
            {{-- <div class="form-group" {{$errors->has('user_id') ? 'is-valid' : ''}}>
                <label for="name">User Id</label>
                {{ Form::text('user_id', '', ['placeholder' => 'User Id','class' => 'form-control']) }}
                {!! $errors->first('user_id','<small style="color:red;">:message</small>') !!}
            </div> --}}
            <div class="form-group" {{ $errors->has('title') ? 'is-invalid' : ''}}>
              <label for="title">Title</label>
              {{ Form::text('title', $post->title, ['placeholder' => 'Title', 'class' => 'form-control']) }}
              {!! $errors->first('title','<small style="color:red;">:message</small>') !!}
            </div>
            <div class="form-group" {{ $errors->has('content') ? 'is-invalid' : ''}}>
              <label for="Contenet">Content</label>
              {{ Form::textarea('content', $post->content, ['placeholder' => 'Content', 'class' => 'form-control','id' => 'editor1']) }}
              {!! $errors->first('content','<small style="color:red;">:message</small>') !!}
            </div>
            <div class="form-group">
                <label for="category">Category</label>
                {{ Form::select('category_id', $data,'',['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                {{ Form::select('tags[]', $tag,'', ['multiple' => 'multiple','class' => 'form-control tag']) }}
            </div>
            <div class="form-group" {{ $errors->has('file') ? 'is-invalid' : ''}}>
              <label for="file">File input</label>
              {{ Form::file('file',['class' => 'form-control']) }}
              {!!$errors->first('file','<small style="color:red;">:message</small>')!!} 
            </div>
            <div class="form-group">
              <img src="{{ asset('storage/upload/'.$post->file) }}" height="100px" width="150px">
            </div> 
            <div class="form-group">
              {{ Form::submit('submit', ['class' => 'btn btn-primary']) }}
            </div>  
        {{ form::close()}}           
    </div>      
@endsection

blog/resources/views/admin/post/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                     <h4 class="card-title">Post</h4>
                    <a role="button" class="btn btn-success" href="post/create">Create Post</a>
                    <div style="float: right;">
                        {!! Form::open(['url' => 'admin/search', 'method' => 'post', 'class'=>'form navbar-form navbar-right searchform']) !!}
                            {{-- {!! Form::text('search', null,['class'=>'form-control','placeholder'=>'Search for a Post...']) !!}
                            {!! Form::submit('Search',['class'=>'btn btn-default']) !!} --}}
                            <div class="input-group mb-3">
                                <input name="search" type="text" class="form-control" placeholder="Search" aria-label="Recipient's username" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                    <div class="table-responsive">
                        <table id="example2" class="table">
                            <thead>
                                <tr>
                                    <th><h4>Id</h4></th>
                                    <th><h4>User Id</h4></th>
                                    <th><h4>Title</h4></th>
                                    <th><h4>Content</h4></th>
                                    <th><h4>View</h4></th>
                                    <th><h4>Cotegory</h4></th>
                                    <th><h4>Tags</h4></th>
                                    <th><h4>Image</h4></th>
                                    <th><h4>Action</h4></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($post as $row)
                                    <tr>
                                        <td>{{$row->id }}</td>
                                        <td>{{$row->user_id }}</td>
                                        <td>{{$row->title }}</td>
                                        <td>{{$row->content }}</td>
                                        <td>{{$row->view_id }}</td>
                                        <td>{{$row->category}}</td>
                                        <td>{{$row->tags}}</td>
                                        <td><img src="{{ asset('storage/upload/'.$row->file) }}" height="100%"  width="100%"></td>
                                        <td>
                                            <a role="button" class="btn btn-primary" href="{{ URL::route('post.edit', $row->id) }}">Edit</a>

                                                <form id="delete-form-{{ $row->id }}" method="post" action="{{ route('post.destroy', $row->id) }}" style="display: none;">
                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}
                                                </form>
                                            <a class="btn btn-danger" href="{{ URL::route('post.destroy', $row->id) }}" onclick="
                                                if (confirm('Are you really want to Delete This Post?')) {
                                                    event.preventDefault();
                                                    document.getElementById('delete-form-{{ $row->id }}').submit();
                                                } else {
                                                    event.preventDefault();
                                                }">Delete
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $post->links() }}
                    </div>
                </div>
            </div>
        </div>    
    </div>    
@endsection

blog/resources/views/admin/post/search.blade.php
@extends('layouts.admin')

@section('content')
	<div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                     <h4 class="card-title">Post</h4>
                    <a role="button" class="btn btn-success" href="post/create" {{-- style="float: right;" --}}>Create Post</a>
					@if (count($articles) === 0)
						<div style="color:red;">Record Not Found</div>
					@elseif (count($articles) >= 1)	
					<div style="float: right;">
			            {!! Form::open(['url' => 'admin/search', 'method' => 'post', 'class'=>'form navbar-form navbar-right searchform']) !!}
			                {!! Form::text('search', null,['class'=>'form-control','placeholder'=>'Search for a Post...']) !!}
			                {!! Form::submit('Search',['class'=>'btn btn-default']) !!}
			            {!! Form::close() !!}
			        </div>
			        <div class="table-responsive" >
						<table id="example2" class="table">
					            <thead>
					                <tr>
					                    <th><h4>Id</h4></th>
					                    <th><h4>Title</h4></th>
					                    <th><h4>Content</h4></th>
					                    <th><h4>Cotegory</h4></th>
					                    <th><h4>Tags</h4></th>
					                    <th><h4>Image</h4></th>
					                    <th><h4>Action</h4></th>
					                </tr>
					            </thead>
					            <tbody>
					                @foreach($articles as $row)
					                    <tr>
					                        <td>{{$row->id }}</td>
					                        <td>{{$row->title }}</td>
					                        <td>{{$row->content }}</td>
					                        <td>{{$row->category_id}}</td>
					                        <td>{{$row->tags}}</td>
					                        <td><img src="{{ asset('storage/upload/'.$row->file) }}" height="100%"  width="100%"></td>
					                        <td>
					                            <a role="button" class="btn btn-primary" href="{{ URL::route('post.edit', $row->id) }}">Edit</a>

					                                <form id="delete-form-{{ $row->id }}" method="post" action="{{ route('post.destroy', $row->id) }}" style="display: none;">
					                                    {{ csrf_field() }}
					                                    {{ method_field('DELETE') }}
					                                </form>
					                            <a class="btn btn-danger" href="{{ URL::route('post.destroy', $row->id) }}" onclick="
					                                if (confirm('Are you really want to Delete This Post?')) {
					                                    event.preventDefault();
					                                    document.getElementById('delete-form-{{ $row->id }}').submit();
					                                } else {
					                                    event.preventDefault();
					                                }">Delete
					                            </a>
					                        </td>
					                    </tr>
					                @endforeach
					            </tbody>
					    </table>
					</div>
	@endif
@endsection