blog/routes/web.php
<?php
Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('post/{slug}', 'HomeController@showPage');
Route::get('category/{category}', 'HomeController@showCategory');
Route::get('search', 'HomeController@search');

Route::group(['prefix' => 'admin'], function(){
	Route::get('login', 'AuthAdminController@loginShowForm');
	Route::post('login', 'AuthAdminController@login')->name('login');
	Route::get('dashboard', 'AdminController@dashboard');
	Route::post('logout', 'AdminController@logout')->name('admin.logout');
	Route::resource('post','AdminPostController');
	Route::resource('category','AdminCategoryController');
	Route::resource('tag','AdminTagController');
	Route::post('search', 'AdminController@search');
});
	

blog/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
}

blog/resources/views/admin/category/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="box-body">
        <h4>Create Category</h4>
        {{ Form::open(['url' => 'admin/category', 'method' => 'post'])}}
            <div class="form-group" {{$errors->has('name') ? 'is-valid' : ''}}>
                <label for="name">Name</label>
                {{ Form::text('name', '', ['placeholder' => 'Name', 'class' => 'form-control']) }}
                {{-- {{ $errors->first('name', '<div style="colore:red;">:message</div>')}} --}}
                {!! $errors->first('name','<small style="color:red;">:message</small>') !!}
            </div>
             <div class="form-group" {{$errors->has('description') ? 'is-valid' : ''}}>
                <label for="name">Description</label>
                {{ Form::textarea('description', '', ['class' => 'form-control'])}}
                {!! $errors->first('description','<small style="color:red;">:message</small>') !!}
            </div>
            <div class="form-group">
                {{ Form::submit('submit', ['class' => 'btn btn-success mr-2']) }}
            </div>  
        {{ form::close()}}
    </div>                               
@endsection

blog/resources/views/admin/category/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="box-body">
        <h4>Edit Category</h4>
        {{ Form::open(['route' => ['category.update', $category->id], 'method' => 'post'])}}
        {{ method_field('PATCH') }}
            <div class="form-group" {{$errors->has('name') ? 'is-valid' : ''}}>
                <label for="name">Name</label>
                {{ Form::text('name', $category->name, ['placeholder' => 'Name', 'class' => 'form-control']) }}
                {!!$errors->first('name', '<div style="color:red";>:message</div>') !!}
            </div>
             <div class="form-group" {{$errors->has('description') ? 'is-valid' : ''}}>
                <label for="name">Description</label>
                {{ Form::textarea('description', $category->description, ['class' => 'form-control'])}}
                {!!$errors->first('description', '<div style="color:red";>:message</div>') !!}
            </div>
            <div class="form-group">
                {{ Form::submit('submit', ['class' => 'btn btn-success mr-2']) }}
            </div>  
        {{ form::close()}}
    </div>                               
@endsection

blog/resources/views/admin/category/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4>CATEGORY</h4>
                    <a role="button" class="btn btn-success" href="{{route('category.create')}}">Create Category</a>
                    <div style="float: right;">
                        {!! Form::open(['url' => 'admin/search', 'method' => 'post', 'class'=>'form navbar-form navbar-right searchform']) !!}
                            {!! Form::text('search', null,['class'=>'form-control','placeholder'=>'Search for a Post...']) !!}
                            {!! Form::submit('Search',['class'=>'btn btn-default']) !!}
                        {!! Form::close() !!}
                    </div>
                    <div class="table-responsive">
                        <table id="example2" class="table">
                            <thead>
                                <tr>
                                    <th><h4>Id</h4></th>
                                    <th><h4>Name</h4></th>
                                    <th><h4>Description</h4></th>
                                    <th><h4>Action</h4></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($category as $row)
                                    <tr>
                                        <td>{{$row->id }}</td>
                                        <td>{{$row->name }}</td>
                                        <td>{{$row->description }}</td>
                                        <td>
                                            <a role="button" class="btn btn-primary" href="{{ URL::route('category.edit', $row->id) }}">Edit</a>

                                                <form id="delete-form-{{ $row->id }}" method="post" action="{{ route('category.destroy', $row->id) }}" style="display: none;">
                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}
                                                </form>
                                            <a class="btn btn-danger" href="{{ URL::route('category.destroy', $row->id) }}" onclick="
                                                if (confirm('Are you really want to Delete This Category?')) {
                                                    event.preventDefault();
                                                    document.getElementById('delete-form-{{ $row->id }}').submit();
                                                } else {
                                                    event.preventDefault();
                                                }">Delete
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $category->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection